name: Generate Snake Animation

on:
  schedule:
    - cron: "0 23 * * *" # roda todo dia às 23h
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Gerar gráfico da cobra
        uses: Platane/snk@v3
        with:
          github_user_name: luca0202
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit e push do arquivo gerado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: actions@github.com
          message: "Gerar gráfico de contribuições (snake)"
          add: "dist/github-contribution-grid-snake.svg"
